sudo: false
language: node_js
node_js:
  - '8'
  - '10'
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test:ci
after_success:
  - yarn build-storybook
deploy:
  local-dir: book
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  name: 'Story-bot'
  on:
    branch: master
